### ISSUE TITLE
unable to hide menubar toolbar statusbar

### ISSUE THREAD

**Issue by sleungcy** [amercier/promise-window#9]
The configuration object is limited to setting height, width and limited number of window settings. Please allow all configurations in the object either by:
1) accept any configuration, concatenate them into string regardless what's passed in.
2) accept string as config

for example, this is currently not achievable: "status=yes,toolbar=no,menubar=no,location=no,scrollbars=1,resizable=1"

**Comment by amercier** [comment]
Hi @sleungcy,

Thanks for opening the issue. I agree this is a legitimate feature. I believe solution (1) is the best, because it provides a less error-prone, and more consistent API.

I don't have the time to implement this right now, so I'll try to look at this, when I have more time.
Of course, if you or anyone would provide a PR, I'll be happy to accept it :)

**Comment by amercier** [comment]
Working on it.

**Comment by amercier** [comment]
Should be fixed in 1.1.0. See #10.
